#version: '3.8'
#services:
#  localstack:
#    image: localstack/localstack:latest
#    container_name: localstack_container
#    ports:
#      - "4566:4566" # LocalStack gateway port
#      - "8000:8000" # DynamoDB port
#    environment:
#      - SERVICES=dynamodb
#      - DEBUG=1
#      - AWS_ACCESS_KEY_ID=test
#      - AWS_SECRET_ACCESS_KEY=test
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"