apiVersion: v1
kind: Service
metadata:
  name: localstack-service
  namespace: default
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 4566
      targetPort: 4566
