apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ddb-ls-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-ddb-ls-poc
  template:
    metadata:
      labels:
        app: aws-ddb-ls-poc
    spec:
      containers:
        - name: aws-ddb-ls-poc
          image: aws-ddb-ls-poc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aws-ddb-ls-poc
spec:
  selector:
    app: aws-ddb-ls-poc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
